[package]
authors = ["Robert Ignat <robert.ignat91@gmail.com>"]
edition = "2018"
name = "thetvdb"
version = "0.0.1"

[dependencies]
failure = "~0.1.5"
serde = { version = "1.0.101", features = ["derive"] }
url = "2.1.0"
serde_json = "1.0.40"
reqwest = { version = "0.10.0-alpha.1", features = ["json"] }
chrono = { version = "~0.4.9", features = ["serde"] }
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
