[package]
authors = ["Robert Ignat <robert.ignat91@gmail.com>"]
edition = "2018"
name = "thetvdb"
version = "0.0.1"

[dependencies]
failure = "0.1.6"
serde = { version = "1.0.102", features = ["derive"] }
url = "2.1.0"
serde_json = "1.0.41"
reqwest = { version = "0.10.0-alpha.2", features = ["json"] }
chrono = { version = "0.4.9", features = ["serde"] }
futures = "0.3.1"
jsonwebtoken = "6.0.1"

[dev-dependencies]
tokio = "0.2.0-alpha.6"
