[package]
name = "thetvdb"
version = "0.1.0-beta.1"
license = "MIT OR Apache-2.0"
description = "TheTVDB API async client"
repository = "https://github.com/roignpar/thetvdb"
readme = "README.md"
authors = ["Robert Ignat <robert.ignat91@gmail.com>"]
keywords = ["thetvdb", "api", "client"]
categories = ["api-bindings", "asynchronous"]
edition = "2018"

[dependencies]
failure = "0.1.6"
serde = { version = "1.0.104", features = ["derive"] }
url = "2.1.1"
serde_json = "1.0.45"
reqwest = { version = "0.10.1", features = ["json"] }
chrono = { version = "0.4.10", features = ["serde"] }
futures = "0.3.1"
jsonwebtoken = "6.0.1"
lazy_static = "1.4.0"

[dev-dependencies]
tokio = { version = "0.2.10", features = ["macros"] }
mockito = "0.22.0"
pem = "0.7.0"
version-sync = "0.8.1"
